### ISSUE TITLE
How to use headers?

### ISSUE THREAD

**Issue by hateCarrot** [mbasso/react-http-request#2] opened 2016-12-01 09:49 UTC
Hi.

This error occurs when using headers.
bundle.js:9485 Warning: Failed prop type: Invalid prop `headers` of type `string` supplied to `Request`, expected `object`.

and I used headers as shown below.
headers='{"Authorization":"ApiKey api_key=blah blah"}'

What is the problem?
Thanks.

**Comment by mbasso** [comment] 2016-12-01 10:04
Hi @hateCarrot,
have you tried the following?
`headers={{"Authorization":"ApiKey api_key=blah blah"}}`

**Comment by hateCarrot** [comment] 2016-12-02 01:14
hi @mbasso 
I changed it to the way you told me. Then the error message was changed.

"XMLHttpRequest cannot load http://konanlink-test.elasticbeanstalk.com/v1/device/list.json. Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response."

The above address is normally returned when running as postman. So it does not seem to be a server problem. Do I have something more to do? Thank you for your reply.

**Comment by hateCarrot** [comment] 2016-12-02 01:16
and Here is request code.

```js
<Request
  url='http://konanlink-test.elasticbeanstalk.com/v1/device/list.json'
  method='post'
  type='application/x-www-form-urlencoded'
  accept='application/json'
  headers={{"Authorization":"ApiKey api_key=blah blah"}}
  verbose={true}
  send='{"offset":"0","limit":"100"}'
>
  {
    ({error, result, loading}) => {
      if (loading) {
        return <div>loading...</div>;
      } else {
        return <div>{ JSON.stringify(result) }</div>;
      }
    }
  }
</Request>
```

**Comment by mbasso** [comment] 2016-12-02 23:39
Unfortunately it seems to be a server problem.
Postman works fine because is a chrome extension and has more privileges than regular web pages (check [this](https://developer.chrome.com/extensions/xhr) for more information).
However, to make your site work, you have to enable [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests).
[Here](http://stackoverflow.com/questions/34119050/cors-request-in-react) you can find a simple explanation of the problem is and [here](http://stackoverflow.com/questions/23823010/how-to-enable-cors-in-angularjs/23826620#23826620) is an example of the headers that you have to add to the reponse.

**Comment by hateCarrot** [comment] 2016-12-06 00:29
Thanks a lot @mbasso 
I'll try to solve the problem as you told me.
Merry Christmas and Happy new year :)

**Comment by mbasso** [comment] 2016-12-10 09:28
Thanks, you too :) 🎄 🎅 
Did you solve the problem with CORS?

**Comment by mbasso** [comment] 2016-12-19 00:12
@hateCarrot Can I close this issue?

**Comment by hateCarrot** [comment] 2016-12-20 08:52
I'm sorry I was late. Thank you for your great help. Close this issue.
Merry Christmas & Happy new year :)

**Closed as completed** 2016-12-20 19:43 UTC
